name: flutterfood
description: Um novo aplicativo Flutter.

# O seguinte define a versão e o número do build do seu aplicativo.
# Um número de versão são três números separados por pontos, como 1.2.43
# seguido por um número de compilação opcional separado por um +.
# Tanto a versão quanto o número do construtor podem ser substituídos em flutter
# compilar especificando --build-name e --build-number, respectivamente.
# No Android, build-name é usado como versionName, enquanto build-number é usado como versionCode.
# Leia mais sobre o controle de versão do Android em https://developer.android.com/studio/publish/versioning
# No iOS, build-name é usado como CFBundleShortVersionString enquanto o build-number é usado como CFBundleVersion.
# Leia mais sobre o controle de versão do iOS em
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # O seguinte adiciona a fonte Cupertino Icons ao seu aplicativo.
  # Use com a classe CupertinoIcons para ícones de estilo iOS.
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.2.0+1
  flutter_cache_manager: ^1.4.1
  curved_navigation_bar: ^0.3.3
  dio: ^3.0.10
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flutter_rating_bar: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  mobx_codegen: ^1.1.0+1

# Para obter informações sobre a parte genérica do DART deste arquivo, consulte o
# página seguinte: https://dart.dev/tools/pub/pubspec

# A seção a seguir é específica para Flutter.
flutter:

  # A linha a seguir garante que a fonte Material Icons seja
  # incluído com seu aplicativo, para que você possa usar os ícones em
  # a classe de ícones de materiais.
  uses-material-design: true

  # Para adicionar ativos ao seu aplicativo, adicione uma seção de ativos, como esta:
  # ativos:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/FlutterFood.png
    - assets/images/IconeFlutterFood.png

  # Um ativo de imagem pode se referir a uma ou mais "variantes" específicas de resolução, consulte
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # Para obter detalhes sobre como adicionar ativos de dependências de pacote, consulte
  # https://flutter.dev/assets-and-images/#from-packages

  # Para adicionar fontes personalizadas ao seu aplicativo, adicione uma seção de fontes aqui,
  # nesta seção de "vibração". Cada entrada nesta lista deve ter um
  # tecla "family" com o nome da família da fonte e uma tecla "fonts" com um
  # lista fornecendo o ativo e outros descritores para a fonte. Para
  # exemplo:
  # fontes:
  #    - família: Schyler
  #      fontes:
  #        - ativo: fonts/Schyler-Regular.ttf
  #        - ativo: fonts/Schyler-Italic.ttf
  #          estilo: itálico
  #    - família: Trajan Pro
  #      fontes:
  #        - ativo: fonts/TrajanPro.ttf
  #        - ativo: fonts/TrajanPro_Bold.ttf
  #          peso: 700
  #
  # Para obter detalhes sobre fontes de dependências de pacotes,
  # consulte https://flutter.dev/custom-fonts/#from-packages